apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: greeting
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

