apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting
          image: greeting-service:1.0
          ports:
            - containerPort: 8080

