apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
        - name: time
          image: time-service:1.0
          ports:
            - containerPort: 8080

